services:
  sensors-api:
    build:
      context: .
      dockerfile: src/Services/Sensor/Sensor.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: