services:
  sensors-api:
    build:
      context: .
      dockerfile: src/Services/Sensor/Sensor.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__SensorDb=Host=db;Port=5432;Database=sensor_db;Username=sensor_user;Password=sensor_dev_password
    develop:
      watch:
        - action: rebuild
          path: src/Services/Sensor/
          ignore:
            - src/Services/Sensor/Sensor.API/obj/
            - src/Services/Sensor/Sensor.API/bin/
          
        - action: sync
          path: src/Services/Sensor/Sensor.API/appsettings.Development.json
          target: /app/appsettings.Development.json
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: